### PR TITLE
Support negated filters

### PR DESCRIPTION
**Pull request by jacwah**
#288

### CODE REVIEW

**Comment by Zomis** [comment]
Could you add a test case for the multi-negation, `!(a && b && c)`, as described in #288 ?

**Comment by jacwah** [comment]
This should really be merged into `develop`, but at the time of creation it depended on code in `effects` not yet merged into the `develop` branch.

**Comment by Zomis** [comment]
Approved. Merge whenever you'd like.

**Comment by jacwah** [comment]
Merged 11ab287af239824e8e4662d1b40b45ab10776753

**Pull request closed without merging**
