### PR TITLE
Implement generic ErrorMessage

### PR DESCRIPTION
**Pull request by jacwah**
See #379.

Cardshifter/HTML-Client#89 is more important as this is merged. There's with this patch close to no feedback at all if anything goes wrong.

### CODE REVIEW

**Comment by Zomis** [comment]
I am wondering if the removal of `MixinWelcomeMessage` might break the JavaFX client (which I'm not sure if that's acceptable or not)

Also, what about adding the "cause", whether or not it's the server that had an internal error or the client that sent a bad request?

**Comment by jacwah** [comment]
I'll test the JavaFX client to see if it works. Completely forgot about `cause`, good thing you reminded me.

**Comment by jacwah** [comment]
I tested logging in with two instances of the JavaFX client, worked like a charm :+1:

**Comment by jacwah** [comment]
I tested the cause changes with JavaFX too.

**Comment by Zomis** [comment]
Approved. Merge whenever you'd like.

Just one suggestion, consider implementing static factory methods, so that 

    new ErrorMessage(e.getMessage(), ErrorMessage.Cause.CLIENT)

can be written as for example:

    ErrorMessage.client(e.getMessage());

**Pull request merged**
